import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  en: {
    community: 'Community',
    arena: 'Arena',
    classroom: 'Classroom',
    leaderboard: 'Leaderboard',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    myProfile: 'My Profile',
    adminDashboard: 'Admin Dashboard',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    back: 'Back',
    loading: 'Loading...',
    new: 'New',
    addProject: '+ Submit',
    switchLight: 'Switch to light mode',
    switchDark: 'Switch to dark mode',
    switchEn: 'Switch to English',
    switchFr: 'Passer en Français',
    notifications: 'Notifications',
    clearAll: 'Clear All',
    noNotifications: 'No new notifications',
    refresh: 'Refresh',
    actions: 'Actions',
    approve: 'Approve',
    reject: 'Reject',
    approved: 'APPROVED',
    rejected: 'REJECTED',
    status: 'Status',
    proof: 'Proof / Notes',
    role: 'Role',
    joined: 'Joined',
    user: 'User',
    users: 'Users',
    admin: 'Admin',
    teacher: 'Teacher',
    student: 'Student',
    teacherLabel: 'Formateur',
    studentLabel: 'Trainee',
    title: 'Title',
    description: 'Description',
    language: 'Language',
    optional: 'Optional',
    file: 'File',
    code: 'Code',
    copy: 'Copy',
    copied: 'Copied!',
    download: 'Download',
    hide: 'Hide',
    show: 'Show',
    remove: 'Remove',
    replace: 'Replace',
    clear: 'Clear',
    chooseFile: 'Choose File',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    tryAgain: 'Try Again',
    goHome: 'Go Home',
    errorId: 'Error ID',
    errorLabel: 'Error:',
    author: 'Author',
    date: 'Date',
    backToEvalify: 'Back to Evalify',
    controlRoom: 'Control Room',
    adminPanel: 'Admin Panel',
    deleteProjectPermanently: 'Delete this project permanently?',
    noProjectsYet: 'No projects yet.',
    comingSoon: 'This section is coming soon.',
    commentsModeration: 'Comments Moderation',
    settings: 'Settings',
    pendingTeacherRequests: 'pending teacher verification requests',
    thisRequest: 'this request',
    reportedComments: 'Reported Comments',
    allComments: 'All Comments',
    dismiss: 'Dismiss',
    reportedBy: 'Reported by',
    reportCount: 'reports',
    noReportedComments: 'No reported comments.',
    noCommentsFound: 'No comments found.',
    searchComments: 'Search comments...',
    classesManagement: 'Classes Management',
    className2: 'Class',
    teacher2: 'Teacher',
    enrolled: 'Enrolled',
    noClassesFound: 'No classes found.',
    searchClasses: 'Search classes...',
    arenaManagement: 'Arena Management',
    challenges2: 'Challenges',
    battles2: 'Battles',
    playerA2: 'Player A',
    playerB2: 'Player B',
    noChallengesFound: 'No challenges found.',
    noBattlesFound: 'No battles found.',

    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    authRequired: 'Authentication Required',
    authRequiredText: 'This is a private platform for OFPPT-EDU. Please sign in with your school email to access the dashboard, community, and classes.',
    authFailed: 'Authentication failed',

    welcomeBackUser: 'Welcome back,',
    dashboardSubtitle: 'OFPPT-EDU Developer Dashboard',
    projects: 'Projects',
    browse: 'Browse',
    newSubmission: 'New Submission',
    goToClassrooms: 'Go to Classrooms',
    enterArena: 'Enter Arena',
    internalNotice: 'Internal Platform Notice',
    internalNoticeText: 'You are logged into the private OFPPT-EDU developer platform. Your submissions, comments, and arena battles are only visible to authorized students and formateurs. Remember to follow the code of conduct during community interactions and peer reviews.',
    shareLearn: 'Share & Learn',
    academicWork: 'Academic Work',
    competeClimb: 'Compete & Climb',
    projectsDesc: 'Submit your recent work to the school community and get instant AI feedback.',
    classroomDesc: 'Access your classes, view upcoming assignments, and submit official coursework.',
    arenaDesc: 'Participate in official teacher challenges or community battles to earn badges.',
    heroTitle: 'Master Your Code with AI',
    heroSubtitle: 'The ultimate platform for OFPPT students to practice, compete, and get instant senior-level feedback.',

    communityProjects: 'Community Projects',
    exploreProjects: 'Explore AI-reviewed projects submitted by developers worldwide.',
    searchPlaceholder: 'Search projects or authors...',
    all: 'All',
    projectsFound: 'projects found',
    noProjectsFound: 'No projects found',
    adjustFilters: 'Try adjusting your filters.',
    firstToSubmit: 'Be the first to submit a project!',
    newest: 'Newest',
    topScored: 'Top Scored',
    mostDiscussed: 'Most Discussed',
    loadingProjects: 'Loading projects...',

    manageUsers: 'Manage Users',
    overview: 'Overview',
    userManagement: 'User Management',
    totalUsers: 'Total Users',
    totalProjects: 'Total Projects',
    totalClasses: 'Total Classes',
    totalBattles: 'Total Battles',
    searchUsers: 'Search users...',
    confirmRoleUpdate: "Are you sure you want to change this user's role to {role}?",
    confirmUserDelete: 'Are you sure you want to delete this user? This action cannot be undone.',
    cannotDemoteLastAdmin: 'Cannot demote the last administrator.',
    adminSubtitle: 'Manage users, content, and platform settings.',
    requests: 'Requests',
    noUsersFound: 'No users found matching',
    pendingRequests: 'Pending Teacher Requests',
    noPendingRequests: 'No pending requests found.',
    failedLoadAdminData: 'Failed to load admin data.',
    failedUpdateRole: 'Failed to update role.',
    failedDeleteUser: 'Failed to delete user.',
    confirmUpdateRequest: 'Are you sure you want to {action} this request?',
    failedUpdateRequest: 'Failed to update request: {message}',
    deleteUserTitle: 'Delete user',
    arenaSection: 'Arena Challenges',

    globalLeaderboard: 'Global Leaderboard',
    discoverTopDevs: 'Discover the top developers and highest-rated projects on Evalify.',
    topProjects: 'Top Projects',
    arenaRankings: 'Arena Rankings',
    rank: 'Rank',
    userProject: 'User / Project',
    tier: 'Tier',
    winRate: 'Win Rate',
    wins: 'Wins',
    losses: 'Losses',
    winStreak: 'Win Streak',
    reputation: 'Reputation',
    rating: 'Rating',
    aiScore: 'AI Score',
    votes: 'votes',
    allTime: 'All Time',
    thisMonth: 'This Month',
    thisWeek: 'This Week',
    by: 'by',
    noData: 'No data available for this category.',
    failedLeaderboard: 'Failed to fetch leaderboard data.',

    addBio: 'Add a bio in your settings.',
    noBioYet: 'No bio yet.',
    joinedIn: 'Joined in',
    badges: 'Badges',
    comments: 'comments',
    projectsCount: 'projects',
    battlesWon: 'battles won',
    avgAiScore: 'Avg AI Score',
    classesTaught: 'Classes Taught',
    officialChallenges: 'Official Challenges',
    noProjects: 'No projects submitted yet.',
    noArena: 'No arena ranking yet. Join a battle to get ranked!',
    noBadges: 'No badges earned yet.',
    winsToNextTier: 'wins to',
    maxTierReached: 'Max Tier Reached!',
    userNotFound: 'User not found.',
    verifyAsTeacher: 'Verify as Formateur',
    proofRequired: 'Please provide proof (badge ID or invite code).',
    requestSent: 'Request Sent!',
    requestReview: 'An administrator will review your proof shortly.',
    verifyTeacherHelp: 'Please provide proof of your teaching status at OFPPT (e.g. an invite code, or badge ID).',
    proofInviteCode: 'Proof / Invite Code',
    verificationPlaceholder: 'Enter your verification details here...',
    submitRequest: 'Submit Request',
    requestSubmitFailed: 'Failed to submit request.',
    season: 'Season',

    myClassroom: 'My Classroom',
    accessCourses: 'Access your courses, submit assignments for AI review, and track your progress.',
    joinClass: 'Join a Class',
    joinClass2: 'Join',
    viewClass: 'View Class',
    students: 'Students',
    assignments: 'Assignments',
    due: 'Due',
    points: 'Points',
    viewFeedback: 'View Feedback',
    myClasses: 'My Classes',
    newAssignment: 'New Assignment',
    submitWork: 'Submit Work',
    inviteCode: 'Invite Code',
    inviteCodeLabel: 'Invite Code',
    inviteCodePlaceholder: '6-digit code (e.g. ABC123)',
    inviteCodeHint: 'Ask your teacher for the 6-digit class code.',
    manageClassroom: 'Manage your students, publish assignments, and use Gemini AI to assist in grading.',
    createNewClass: 'Create New Class',
    loadingClasses: 'Loading your classes...',
    noClassesYet: 'No Classes Yet',
    noClassesTeacher: "You haven't created any classes. Start by creating one to invite students.",
    noClassesStudent: "You haven't joined any classes yet. Get an invite code from your teacher.",
    createFirstClass: 'Create Your First Class',
    joinAClass: 'Join a Class',
    className: 'Class Name',
    classPlaceholder: 'e.g. Advanced React Architecture',
    classDescript: 'What will students learn in this class?',
    createClass: 'Create Class',
    learningTogether: 'Learning and building together on Evalify.',
    failedJoinClass: 'Failed to join class.',
    failedCreateClass: 'Failed to create class.',

    loadingClassDetails: 'Loading class details...',
    classNotFound: 'Class Not Found',
    backToClassroom: 'Back to Classroom',
    backToMyClasses: 'Back to My Classes',
    welcomeLearningSpace: 'Welcome to this learning space on Evalify.',
    shareWithStudents: 'Share this with your students',
    noAssignmentsPublished: 'No assignments published yet.',
    noStudentsJoined: 'No students joined yet.',
    noDeadline: 'No deadline',
    instructionsAttached: 'Instructions are attached as a file.',
    viewSubmissions: 'View Submissions',
    addDescriptionOrAttach: 'Add a description or attach a file for students.',
    addDescriptionOrKeepAttach: 'Add a description or keep/attach a file for students.',
    failedPublishAssignment: 'Failed to publish assignment.',
    failedUpdateAssignment: 'Failed to update assignment.',
    deleteAssignmentConfirm: 'Delete this assignment? This cannot be undone.',
    pleaseUploadZip: 'Please upload a .zip file.',
    assignmentSubmission: 'Assignment submission',
    uploadFailedRetry: 'Upload failed. Please try again.',
    editAssignment: 'Edit Assignment',
    requirements: 'Description / Requirements',
    assignmentTitlePlaceholder: 'e.g. Build a Task Manager API',
    assignmentRequirementsPlaceholder: 'Write a short summary, or attach the full assignment brief below...',
    maxPoints: 'Max Points',
    deadlineOptional: 'Deadline (Optional)',
    assignmentFile: 'Assignment File',
    attachBrief: 'Attach a brief or resources',
    allowedAssignmentFiles: 'PDF, Word, slides, spreadsheets, images, text, or ZIP up to 50 MB',
    currentAttachment: 'Current attachment',
    attachmentWillBeRemoved: 'The current attachment will be removed.',
    undo: 'Undo',
    noFileAttached: 'No file attached yet.',
    publishAssignment: 'Publish Assignment',
    successfullySubmitted: 'Successfully Submitted!',
    assignmentSubmittedText: 'You can now view your submission and choose to run an AI analysis.',
    selectProjectZip: 'Select your project .ZIP file for evaluation.',
    processing: 'Processing...',
    chooseZipFile: 'Choose ZIP File',

    projectTitle: 'Project Title',
    aiAnalysis: 'AI Analysis',
    teacherFeedback: 'Teacher Feedback',
    strengths: 'Strengths',
    improvements: 'Improvements',
    metrics: 'Metrics Analysis',
    codeQuality: 'Code Quality',
    security: 'Security',
    performance: 'Performance',
    scalability: 'Scalability',
    teacherGrade: 'Teacher Grade',
    categoryScores: 'Category Scores',
    projectNotFound: 'Project not found.',
    unableUpdateProject: 'Unable to update project.',
    unableDeleteProject: 'Unable to delete project.',
    editProject: 'Edit Project',
    githubUrl: 'GitHub URL',
    liveDemoUrl: 'Live Demo URL',
    backToCommunity: 'Back to Community',
    ratings: 'ratings',
    githubStars: 'GitHub Stars',
    liveDemo: 'Live Demo',
    downloadSourceCode: 'Download Source Code',
    deleteProjectConfirm: 'Delete this project? This action cannot be undone.',
    deleteProjectShortConfirm: 'Delete this project?',
    noAiAnalysisTitle: 'No AI analysis yet',
    noAiAnalysisText: 'This project has not been evaluated by AI yet. Click to start the analysis now.',
    discussions: 'Discussions',
    shareThoughts: 'Share your thoughts on this project...',
    posting: 'Posting...',
    postComment: 'Post Comment',
    signInDiscussion: 'Please sign in to join the discussion.',
    deleteCommentConfirm: 'Delete comment?',
    failedDeleteComment: 'Failed to delete comment.',
    noCommentsYet: 'No comments yet. Be the first to share your feedback!',
    rateProject: 'Rate this project',
    cannotRateOwnProject: 'You cannot rate your own project.',
    signInToRate: 'Sign in to rate this project.',
    failedAddComment: 'Failed to add comment.',
    reply: 'Reply',
    replying: 'Replying...',
    postReply: 'Post Reply',
    hideReplies: 'Hide replies',
    showReplies: 'Show {count} replies',
    like: 'Like',
    liked: 'Liked',
    report: 'Report',
    reportCommentTitle: 'Report Comment',
    reportReason: 'Reason for report',
    reportReasonPlaceholder: 'Describe why you are reporting this comment...',
    submitReport: 'Submit Report',
    reported: 'Reported',
    commentReported: 'Comment has been reported',
    adminCannotComment: 'Administrators cannot participate in discussions.',
    adminCannotRate: 'Administrators cannot rate projects.',

    submissionReceived: 'Submission Received',
    submitProject: 'Submit Project',
    fullProjectZip: 'Full Project (ZIP)',
    fullProjectZipHint: 'A ZIP archive of your complete project folder',
    htmlCss: 'HTML / CSS',
    htmlCssHint: 'A single HTML file, CSS file, or a ZIP containing them',
    pythonScript: 'Python Script',
    pythonScriptHint: 'A .py file or a ZIP with multiple Python scripts',
    sqlQueries: 'SQL Queries',
    sqlQueriesHint: 'A .sql file with your queries or schema',
    localFile: 'Local File',
    github: 'GitHub',
    submissionType: 'Submission Type',
    optionalRepoName: '(Optional - repo name will be used)',
    myProjectPlaceholder: 'My project...',
    briefDescriptionPlaceholder: 'Brief description...',
    invalidFileType: 'Invalid file type. Allowed: {types}',
    fileRequired: 'A file is required.',
    githubUrlRequired: 'A GitHub URL is required.',
    uploadFailed: 'Upload failed.',
    githubRepositoryUrl: 'GitHub Repository URL',
    publicRepoHint: 'Must be a public repository. The default branch will be fetched automatically.',
    aiOptionalTitle: 'AI analysis is optional.',
    aiOptionalText: 'Your project will be saved immediately. You can trigger AI analysis from the project page whenever you are ready.',
    savingProject: 'Saving...',
    projectSubmitted: 'Project Submitted!',
    visitProjectPage: 'Visit your project page to trigger the AI analysis when you are ready.',
    viewInCommunity: 'View in Community',
    clickChooseFile: 'Click to choose a {types} file',

    loadingSubmissions: 'Loading submissions...',
    assignmentNotFound: 'Assignment Not Found',
    backToClass: 'Back to Class',
    submissionsTitle: 'Submissions:',
    studentsSubmitted: 'student(s) submitted their work.',
    searchByStudent: 'Search by student name...',
    submittedAt: 'Submitted At',
    noMatchingSubmissions: 'No matching submissions found.',
    late: 'LATE',
    graded: 'GRADED',
    pending: 'PENDING',
    review: 'Review',
    loadingSubmission: 'Loading submission...',
    submissionNotFound: 'Submission Not Found',
    submittedFor: 'Submitted for',
    lateSubmission: 'LATE SUBMISSION',
    gradingDashboard: 'Grading Dashboard',
    teacherScoreLabel: 'Teacher Score',
    enterFinalGrade: 'Enter final grade...',
    feedbackForStudent: 'Feedback for Student',
    feedbackPlaceholder: 'Write your comments and suggestions here...',
    publishGrade: 'Publish Grade',
    gradeSaved: 'Grade saved successfully!',
    failedSaveGrade: 'Failed to save grade.',
    gradedBy: 'Graded by',
    onDate: 'on',
    noCommentProvided: 'No comment provided.',
    noStrengths: 'No specific strengths noted.',
    noImprovements: 'No major improvements suggested.',
    aiAnalysisDescription: 'AI analysis provides detailed feedback on code quality, security, and performance.',

    codingBattles: 'Coding Battles',
    activeChallenges: 'Active Challenges',
    ranking: 'Ranking',
    createChallenge: 'Create Challenge',
    challengeTitle: 'Challenge Title',
    challengeTitlePlaceholder: 'e.g. Build a REST API in 2 hours',
    challengePrompt: 'Challenge Prompt',
    challengePromptPlaceholder: 'Describe the challenge in detail...',
    challengeType: 'Challenge Type',
    communityMatch: 'Community (Friendly Match)',
    officialGraded: 'Official (Graded Coursework)',
    difficulty: 'Difficulty',
    duration: 'Duration',
    creating: 'Creating...',
    titlePromptRequired: 'Title and prompt are required.',
    failedCreateChallenge: 'Failed to create challenge.',
    anyLanguage: 'Any',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    quickDuration: '2 hours',
    standardDuration: '48 hours',
    royaleDuration: '1 week',
    statusPending: 'Pending',
    statusActive: 'Active',
    statusJudging: 'Judging',
    statusComplete: 'Complete',
    statusPendingDesc: 'Waiting for the battle to begin.',
    statusActiveDesc: 'Both players can now submit their solutions.',
    statusJudgingDesc: 'AI is evaluating both submissions...',
    statusCompleteDesc: 'Battle concluded. See the results below.',
    challengePlayer: 'Challenge a Player',
    challengeLabel: 'Challenge:',
    selectOpponent: 'Select Opponent',
    searchByName: 'Search by name...',
    tierLabel: 'Tier:',
    selectOpponentError: 'Please select an opponent to challenge.',
    failedInitiateBattle: 'Failed to initiate battle.',
    initiating: 'Initiating...',
    initiateBattle: 'Initiate Battle',
    codeArena: 'Code Arena',
    noBattlesYet: 'No battles yet',
    challengeSomeoneText: 'Challenge someone from the Challenges tab to start a battle.',
    noChallengesYet: 'No challenges yet',
    firstCreateChallenge: 'Be the first - create a challenge!',
    signInCreateChallenge: 'Sign in to create a challenge.',
    officialChallenge: 'Official Challenge',
    battle: 'Battle',
    winner: 'Winner',
    defeated: 'Defeated',

    loadingBattle: 'Loading battle...',
    battleNotFound: 'Battle not found.',
    backToArena: 'Back to Arena',
    player1: 'Player 1',
    player2: 'Player 2',
    submitted: 'Submitted',
    challengePending: 'Challenge Pending',
    challengedText: 'You have been challenged to a coding battle! Accept to start the timer and open the editor.',
    acceptChallenge: 'Accept Challenge',
    waitingForAcceptance: 'Waiting for {name} to accept your challenge...',
    liveEditor: 'Live Editor',
    uploadZip: 'Upload ZIP',
    submitYourSolution: 'Submit Your Solution',
    uploadZipText: 'Upload a .zip of your project. Gemini AI will analyze and score it immediately.',
    uploadingAnalyzing: 'Uploading & Analyzing...',
    uploadZipSolution: 'Upload .ZIP Solution',
    runCode: 'Run Code',
    executionOutput: 'Execution Output',
    processSignal: 'Process exited with signal {signal}',
    noOutput: 'Program finished with no output.',
    analyzing: 'Analyzing...',
    submitSolution: 'Submit Solution',
    waitingOpponent: 'Waiting for your opponent to submit their solution...',
    battleResults: 'Battle Results',
    judgingInProgress: 'Judging in Progress',
    noSubmissionYet: 'No submission yet',
    writeSolutionHere: '// Write your solution here\n',
    arenaBattleSubmission: 'Arena battle submission',
    failedGenerateZip: 'Failed to generate ZIP file from editor.',
    executionFailed: 'Execution failed',

    liveWebPreview: 'Live Web Preview',
    terminalEnvironment: 'Terminal Environment',
    guiPreview: 'GUI Preview',
    webPreviewTitle: 'Web Preview',
    noFilesFound: 'No files found to execute',
    running: 'Running...',
    programExited: 'Program exited with code {code}',
    clickRunCode: 'Click "Run Code" to execute this project in the sandbox',
    noScreenshot: 'No screenshot provided for this GUI project.',
    uploading: 'Uploading...',
    uploadScreenshot: 'Upload Screenshot',
    guiCannotRun: 'GUI applications cannot run in the browser. Run it locally:',
    cloneCommandCopied: 'Clone command copied!',

    noAnalysisTarget: 'No project or submission ID provided.',
    aiAnalysisFailed: 'AI analysis failed. Please try again.',
    analyzingInProgress: 'Analysis in progress...',
    reanalyzeWithAi: 'Re-analyze with AI',
    analyzeWithAi: 'Analyze with AI',

    shareProject: 'Share Project',
    shareBattle: 'Share Battle',
    customMessageOptional: 'Custom Message (Optional)',
    addPersonalMessage: 'Add a personal message...',
    generateShareLink: 'Generate Share Link',
    analytics: 'Analytics',
    shareAnalytics: 'Share Analytics',
    totalClicks: 'Total Clicks',
    uniqueClicks: 'Unique Clicks',
    shareDefaultProject: 'Check out this project on Evalify!',
    shareDefaultBattle: 'Check out this coding battle on Evalify!',

    errorBoundaryTitle: 'Oops! Something went wrong',
    errorBoundaryText: "We encountered an unexpected error. Don't worry, our team has been notified and is working on a fix.",
    developmentErrorDetails: 'Development Error Details',
    componentStack: 'Component Stack:',
    files: 'Files',
    filenamePlaceholder: 'filename.js',
  },
  fr: {
    community: 'Communauté',
    arena: 'Arène',
    classroom: 'Classe',
    leaderboard: 'Classement',
    signIn: 'Connexion',
    signOut: 'Déconnexion',
    myProfile: 'Mon profil',
    adminDashboard: 'Tableau de bord admin',
    submit: 'Soumettre',
    cancel: 'Annuler',
    save: 'Enregistrer',
    edit: 'Modifier',
    delete: 'Supprimer',
    back: 'Retour',
    loading: 'Chargement...',
    new: 'Nouveau',
    addProject: '+ Soumettre',
    switchLight: 'Passer en mode clair',
    switchDark: 'Passer en mode sombre',
    switchEn: 'Switch to English',
    switchFr: 'Passer en Français',
    notifications: 'Notifications',
    clearAll: 'Tout effacer',
    noNotifications: 'Aucune nouvelle notification',
    refresh: 'Actualiser',
    actions: 'Actions',
    approve: 'Approuver',
    reject: 'Rejeter',
    approved: 'APPROUVÉE',
    rejected: 'REJETÉE',
    status: 'Statut',
    proof: 'Preuve / Notes',
    role: 'Rôle',
    joined: 'Inscrit',
    user: 'Utilisateur',
    users: 'Utilisateurs',
    admin: 'Admin',
    teacher: 'Formateur',
    student: 'Étudiant',
    teacherLabel: 'Formateur',
    studentLabel: 'Stagiaire',
    title: 'Titre',
    description: 'Description',
    language: 'Langage',
    optional: 'Facultatif',
    file: 'Fichier',
    code: 'Code',
    copy: 'Copier',
    copied: 'Copié !',
    download: 'Télécharger',
    hide: 'Masquer',
    show: 'Afficher',
    remove: 'Retirer',
    replace: 'Remplacer',
    clear: 'Effacer',
    chooseFile: 'Choisir un fichier',
    saving: 'Enregistrement...',
    saveChanges: 'Enregistrer les modifications',
    tryAgain: 'Réessayer',
    goHome: 'Accueil',
    errorId: 'ID d\'erreur',
    errorLabel: 'Erreur :',
    author: 'Auteur',
    date: 'Date',
    backToEvalify: 'Retour à Evalify',
    controlRoom: 'Salle de contrôle',
    adminPanel: 'Panneau admin',
    deleteProjectPermanently: 'Supprimer définitivement ce projet ?',
    noProjectsYet: 'Aucun projet pour le moment.',
    comingSoon: 'Cette section arrive bientôt.',
    commentsModeration: 'Modération des commentaires',
    settings: 'Paramètres',
    pendingTeacherRequests: 'demandes de vérification de formateur en attente',
    thisRequest: 'cette demande',
    reportedComments: 'Commentaires signalés',
    allComments: 'Tous les commentaires',
    dismiss: 'Ignorer',
    reportedBy: 'Signalé par',
    reportCount: 'signalements',
    noReportedComments: 'Aucun commentaire signalé.',
    noCommentsFound: 'Aucun commentaire trouvé.',
    searchComments: 'Rechercher des commentaires...',
    classesManagement: 'Gestion des classes',
    className2: 'Classe',
    teacher2: 'Formateur',
    enrolled: 'Inscrits',
    noClassesFound: 'Aucune classe trouvée.',
    searchClasses: 'Rechercher des classes...',
    arenaManagement: 'Gestion de l\'arène',
    challenges2: 'Défis',
    battles2: 'Duels',
    playerA2: 'Joueur A',
    playerB2: 'Joueur B',
    noChallengesFound: 'Aucun défi trouvé.',
    noBattlesFound: 'Aucun duel trouvé.',

    welcomeBack: 'Bon retour',
    createAccount: 'Créer un compte',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    fullName: 'Nom complet',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    dontHaveAccount: 'Vous n\'avez pas encore de compte ?',
    authRequired: 'Authentification requise',
    authRequiredText: 'Cette plateforme privée est réservée à OFPPT-EDU. Connectez-vous avec votre e-mail scolaire pour accéder au tableau de bord, à la communauté et aux classes.',
    authFailed: 'Échec de l\'authentification',

    welcomeBackUser: 'Bienvenue,',
    dashboardSubtitle: 'Tableau de bord développeur OFPPT-EDU',
    projects: 'Projets',
    browse: 'Explorer',
    newSubmission: 'Nouvelle soumission',
    goToClassrooms: 'Aller aux classes',
    enterArena: 'Entrer dans l\'arène',
    internalNotice: 'Avis de plateforme interne',
    internalNoticeText: 'Vous êtes connecté à la plateforme privée des développeurs OFPPT-EDU. Vos soumissions, commentaires et duels d\'arène ne sont visibles que par les étudiants et formateurs autorisés. Respectez le code de conduite lors des échanges et des évaluations entre pairs.',
    shareLearn: 'Partager et apprendre',
    academicWork: 'Travail académique',
    competeClimb: 'Compétition et progression',
    projectsDesc: 'Soumettez vos travaux récents à la communauté scolaire et obtenez un retour IA instantané.',
    classroomDesc: 'Accédez à vos classes, consultez les prochains devoirs et soumettez vos travaux officiels.',
    arenaDesc: 'Participez aux défis officiels des formateurs ou aux batailles communautaires pour gagner des badges.',
    heroTitle: 'Maîtrisez votre code avec l\'IA',
    heroSubtitle: 'La plateforme ultime pour les étudiants de l\'OFPPT qui veulent pratiquer, rivaliser et obtenir un retour de niveau senior.',

    communityProjects: 'Projets communautaires',
    exploreProjects: 'Explorez les projets évalués par l\'IA soumis par des développeurs du monde entier.',
    searchPlaceholder: 'Rechercher des projets ou des auteurs...',
    all: 'Tous',
    projectsFound: 'projets trouvés',
    noProjectsFound: 'Aucun projet trouvé',
    adjustFilters: 'Essayez de modifier vos filtres.',
    firstToSubmit: 'Soyez le premier à soumettre un projet !',
    newest: 'Plus récents',
    topScored: 'Mieux notés',
    mostDiscussed: 'Plus discutés',
    loadingProjects: 'Chargement des projets...',

    manageUsers: 'Gérer les utilisateurs',
    overview: 'Aperçu',
    userManagement: 'Gestion des utilisateurs',
    totalUsers: 'Total utilisateurs',
    totalProjects: 'Total projets',
    totalClasses: 'Total classes',
    totalBattles: 'Total duels',
    searchUsers: 'Rechercher des utilisateurs...',
    confirmRoleUpdate: 'Voulez-vous vraiment changer le rôle de cet utilisateur en {role} ?',
    confirmUserDelete: 'Voulez-vous vraiment supprimer cet utilisateur ? Cette action est irréversible.',
    cannotDemoteLastAdmin: 'Impossible de rétrograder le dernier administrateur.',
    adminSubtitle: 'Gérez les utilisateurs, le contenu et les paramètres de la plateforme.',
    requests: 'Demandes',
    noUsersFound: 'Aucun utilisateur trouvé pour',
    pendingRequests: 'Demandes de formateur en attente',
    noPendingRequests: 'Aucune demande en attente.',
    failedLoadAdminData: 'Impossible de charger les données admin.',
    failedUpdateRole: 'Impossible de modifier le rôle.',
    failedDeleteUser: 'Impossible de supprimer l\'utilisateur.',
    confirmUpdateRequest: 'Voulez-vous vraiment {action} cette demande ?',
    failedUpdateRequest: 'Impossible de mettre à jour la demande : {message}',
    deleteUserTitle: 'Supprimer l\'utilisateur',
    arenaSection: 'Défis Arène',

    globalLeaderboard: 'Classement global',
    discoverTopDevs: 'Découvrez les meilleurs développeurs et les projets les mieux notés sur Evalify.',
    topProjects: 'Meilleurs projets',
    arenaRankings: 'Classement arène',
    rank: 'Rang',
    userProject: 'Utilisateur / Projet',
    tier: 'Palier',
    winRate: 'Taux de victoire',
    wins: 'Victoires',
    losses: 'Défaites',
    winStreak: 'Série',
    reputation: 'Réputation',
    rating: 'Note',
    aiScore: 'Score IA',
    votes: 'votes',
    allTime: 'Tout le temps',
    thisMonth: 'Ce mois',
    thisWeek: 'Cette semaine',
    by: 'par',
    noData: 'Aucune donnée disponible pour cette catégorie.',
    failedLeaderboard: 'Impossible de récupérer le classement.',

    addBio: 'Ajoutez une bio dans vos paramètres.',
    noBioYet: 'Pas encore de bio.',
    joinedIn: 'Inscrit en',
    badges: 'Badges',
    comments: 'commentaires',
    projectsCount: 'projets',
    battlesWon: 'duels gagnés',
    avgAiScore: 'Score IA moyen',
    classesTaught: 'Classes enseignées',
    officialChallenges: 'Défis officiels',
    noProjects: 'Aucun projet soumis pour le moment.',
    noArena: 'Pas encore de classement arène. Rejoignez un duel pour être classé !',
    noBadges: 'Aucun badge obtenu pour le moment.',
    winsToNextTier: 'victoires jusqu\'à',
    maxTierReached: 'Palier maximum atteint !',
    userNotFound: 'Utilisateur introuvable.',
    verifyAsTeacher: 'Vérifier comme formateur',
    proofRequired: 'Veuillez fournir une preuve (ID de badge ou code d\'invitation).',
    requestSent: 'Demande envoyée !',
    requestReview: 'Un administrateur examinera votre preuve bientôt.',
    verifyTeacherHelp: 'Veuillez fournir une preuve de votre statut de formateur à l\'OFPPT (par exemple un code d\'invitation ou un ID de badge).',
    proofInviteCode: 'Preuve / Code d\'invitation',
    verificationPlaceholder: 'Saisissez vos informations de vérification...',
    submitRequest: 'Envoyer la demande',
    requestSubmitFailed: 'Impossible d\'envoyer la demande.',
    season: 'Saison',

    myClassroom: 'Ma classe',
    accessCourses: 'Accédez à vos cours, soumettez des devoirs pour évaluation par l\'IA et suivez vos progrès.',
    joinClass: 'Rejoindre une classe',
    joinClass2: 'Rejoindre',
    viewClass: 'Voir la classe',
    students: 'Étudiants',
    assignments: 'Devoirs',
    due: 'À rendre',
    points: 'Points',
    viewFeedback: 'Voir le retour',
    myClasses: 'Mes classes',
    newAssignment: 'Nouveau devoir',
    submitWork: 'Soumettre mon travail',
    inviteCode: 'Code d\'invitation',
    inviteCodeLabel: 'Code d\'invitation',
    inviteCodePlaceholder: 'Code à 6 caractères (ex. ABC123)',
    inviteCodeHint: 'Demandez à votre formateur le code de classe à 6 caractères.',
    manageClassroom: 'Gérez vos étudiants, publiez des devoirs et utilisez l\'IA Gemini pour aider à la notation.',
    createNewClass: 'Créer une classe',
    loadingClasses: 'Chargement de vos classes...',
    noClassesYet: 'Aucune classe',
    noClassesTeacher: 'Vous n\'avez pas encore créé de classe. Commencez par en créer une pour inviter des étudiants.',
    noClassesStudent: 'Vous n\'avez pas encore rejoint de classe. Demandez un code d\'invitation à votre formateur.',
    createFirstClass: 'Créer votre première classe',
    joinAClass: 'Rejoindre une classe',
    className: 'Nom de la classe',
    classPlaceholder: 'ex. Architecture React avancée',
    classDescript: 'Qu\'apprendront les étudiants dans cette classe ?',
    createClass: 'Créer la classe',
    learningTogether: 'Apprendre et construire ensemble sur Evalify.',
    failedJoinClass: 'Impossible de rejoindre la classe.',
    failedCreateClass: 'Impossible de créer la classe.',

    loadingClassDetails: 'Chargement des détails de la classe...',
    classNotFound: 'Classe introuvable',
    backToClassroom: 'Retour à la classe',
    backToMyClasses: 'Retour à mes classes',
    welcomeLearningSpace: 'Bienvenue dans cet espace d\'apprentissage sur Evalify.',
    shareWithStudents: 'Partagez ce code avec vos étudiants',
    noAssignmentsPublished: 'Aucun devoir publié pour le moment.',
    noStudentsJoined: 'Aucun étudiant n\'a rejoint la classe.',
    noDeadline: 'Pas de date limite',
    instructionsAttached: 'Les consignes sont jointes dans un fichier.',
    viewSubmissions: 'Voir les soumissions',
    addDescriptionOrAttach: 'Ajoutez une description ou joignez un fichier pour les étudiants.',
    addDescriptionOrKeepAttach: 'Ajoutez une description ou conservez/joignez un fichier pour les étudiants.',
    failedPublishAssignment: 'Impossible de publier le devoir.',
    failedUpdateAssignment: 'Impossible de modifier le devoir.',
    deleteAssignmentConfirm: 'Supprimer ce devoir ? Cette action est irréversible.',
    pleaseUploadZip: 'Veuillez téléverser un fichier .zip.',
    assignmentSubmission: 'Soumission de devoir',
    uploadFailedRetry: 'Échec du téléversement. Veuillez réessayer.',
    editAssignment: 'Modifier le devoir',
    requirements: 'Description / Exigences',
    assignmentTitlePlaceholder: 'ex. Construire une API de gestion de tâches',
    assignmentRequirementsPlaceholder: 'Rédigez un court résumé ou joignez le sujet complet ci-dessous...',
    maxPoints: 'Points max',
    deadlineOptional: 'Date limite (facultatif)',
    assignmentFile: 'Fichier du devoir',
    attachBrief: 'Joindre un sujet ou des ressources',
    allowedAssignmentFiles: 'PDF, Word, présentations, tableurs, images, texte ou ZIP jusqu\'à 50 Mo',
    currentAttachment: 'Pièce jointe actuelle',
    attachmentWillBeRemoved: 'La pièce jointe actuelle sera retirée.',
    undo: 'Annuler',
    noFileAttached: 'Aucun fichier joint.',
    publishAssignment: 'Publier le devoir',
    successfullySubmitted: 'Soumission réussie !',
    assignmentSubmittedText: 'Vous pouvez maintenant voir votre soumission et lancer une analyse IA.',
    selectProjectZip: 'Sélectionnez le fichier .ZIP de votre projet pour l\'évaluation.',
    processing: 'Traitement...',
    chooseZipFile: 'Choisir le fichier ZIP',

    projectTitle: 'Titre du projet',
    aiAnalysis: 'Analyse IA',
    teacherFeedback: 'Retour du formateur',
    strengths: 'Points forts',
    improvements: 'Améliorations',
    metrics: 'Analyse des métriques',
    codeQuality: 'Qualité du code',
    security: 'Sécurité',
    performance: 'Performance',
    scalability: 'Évolutivité',
    teacherGrade: 'Note du formateur',
    categoryScores: 'Scores par catégorie',
    projectNotFound: 'Projet introuvable.',
    unableUpdateProject: 'Impossible de modifier le projet.',
    unableDeleteProject: 'Impossible de supprimer le projet.',
    editProject: 'Modifier le projet',
    githubUrl: 'URL GitHub',
    liveDemoUrl: 'URL de démo en ligne',
    backToCommunity: 'Retour à la communauté',
    ratings: 'notes',
    githubStars: 'étoiles GitHub',
    liveDemo: 'Démo en ligne',
    downloadSourceCode: 'Télécharger le code source',
    deleteProjectConfirm: 'Supprimer ce projet ? Cette action est irréversible.',
    deleteProjectShortConfirm: 'Supprimer ce projet ?',
    noAiAnalysisTitle: 'Pas encore d\'analyse IA',
    noAiAnalysisText: 'Ce projet n\'a pas encore été évalué par l\'IA. Cliquez pour lancer l\'analyse maintenant.',
    discussions: 'Discussions',
    shareThoughts: 'Partagez votre avis sur ce projet...',
    posting: 'Publication...',
    postComment: 'Publier le commentaire',
    signInDiscussion: 'Connectez-vous pour participer à la discussion.',
    deleteCommentConfirm: 'Supprimer le commentaire ?',
    failedDeleteComment: 'Impossible de supprimer le commentaire.',
    noCommentsYet: 'Aucun commentaire pour le moment. Soyez le premier à donner votre avis !',
    rateProject: 'Noter ce projet',
    cannotRateOwnProject: 'Vous ne pouvez pas noter votre propre projet.',
    signInToRate: 'Connectez-vous pour noter ce projet.',
    failedAddComment: 'Impossible d\'ajouter le commentaire.',
    reply: 'Répondre',
    replying: 'Réponse...',
    postReply: 'Publier la réponse',
    hideReplies: 'Masquer les réponses',
    showReplies: 'Afficher les {count} réponses',
    like: 'J\'aime',
    liked: 'Aimé',
    report: 'Signaler',
    reportCommentTitle: 'Signaler un commentaire',
    reportReason: 'Raison du signalement',
    reportReasonPlaceholder: 'Décrivez pourquoi vous signalez ce commentaire...',
    submitReport: 'Soumettre le signalement',
    reported: 'Signalé',
    commentReported: 'Le commentaire a été signalé',
    adminCannotComment: 'Les administrateurs ne peuvent pas participer aux discussions.',
    adminCannotRate: 'Les administrateurs ne peuvent pas noter les projets.',

    submissionReceived: 'Soumission reçue',
    submitProject: 'Soumettre un projet',
    fullProjectZip: 'Projet complet (ZIP)',
    fullProjectZipHint: 'Une archive ZIP du dossier complet de votre projet',
    htmlCss: 'HTML / CSS',
    htmlCssHint: 'Un fichier HTML, un fichier CSS ou un ZIP qui les contient',
    pythonScript: 'Script Python',
    pythonScriptHint: 'Un fichier .py ou un ZIP avec plusieurs scripts Python',
    sqlQueries: 'Requêtes SQL',
    sqlQueriesHint: 'Un fichier .sql avec vos requêtes ou votre schéma',
    localFile: 'Fichier local',
    github: 'GitHub',
    submissionType: 'Type de soumission',
    optionalRepoName: '(Facultatif - le nom du dépôt sera utilisé)',
    myProjectPlaceholder: 'Mon projet...',
    briefDescriptionPlaceholder: 'Brève description...',
    invalidFileType: 'Type de fichier invalide. Autorisés : {types}',
    fileRequired: 'Un fichier est requis.',
    githubUrlRequired: 'Une URL GitHub est requise.',
    uploadFailed: 'Échec du téléversement.',
    githubRepositoryUrl: 'URL du dépôt GitHub',
    publicRepoHint: 'Le dépôt doit être public. La branche par défaut sera récupérée automatiquement.',
    aiOptionalTitle: 'L\'analyse IA est facultative.',
    aiOptionalText: 'Votre projet sera enregistré immédiatement. Vous pourrez lancer l\'analyse IA depuis la page du projet quand vous serez prêt.',
    savingProject: 'Enregistrement...',
    projectSubmitted: 'Projet soumis !',
    visitProjectPage: 'Visitez la page du projet pour lancer l\'analyse IA quand vous serez prêt.',
    viewInCommunity: 'Voir dans la communauté',
    clickChooseFile: 'Cliquez pour choisir un fichier {types}',

    loadingSubmissions: 'Chargement des soumissions...',
    assignmentNotFound: 'Devoir introuvable',
    backToClass: 'Retour à la classe',
    submissionsTitle: 'Soumissions :',
    studentsSubmitted: 'étudiant(s) ont soumis leur travail.',
    searchByStudent: 'Rechercher par nom d\'étudiant...',
    submittedAt: 'Soumis le',
    noMatchingSubmissions: 'Aucune soumission correspondante.',
    late: 'EN RETARD',
    graded: 'NOTÉ',
    pending: 'EN ATTENTE',
    review: 'Réviser',
    loadingSubmission: 'Chargement de la soumission...',
    submissionNotFound: 'Soumission introuvable',
    submittedFor: 'Soumis pour',
    lateSubmission: 'SOUMISSION EN RETARD',
    gradingDashboard: 'Tableau de notation',
    teacherScoreLabel: 'Note du formateur',
    enterFinalGrade: 'Saisir la note finale...',
    feedbackForStudent: 'Retour pour l\'étudiant',
    feedbackPlaceholder: 'Écrivez vos commentaires et suggestions ici...',
    publishGrade: 'Publier la note',
    gradeSaved: 'Note enregistrée avec succès !',
    failedSaveGrade: 'Impossible d\'enregistrer la note.',
    gradedBy: 'Noté par',
    onDate: 'le',
    noCommentProvided: 'Aucun commentaire fourni.',
    noStrengths: 'Aucun point fort spécifique noté.',
    noImprovements: 'Aucune amélioration majeure suggérée.',
    aiAnalysisDescription: 'L\'analyse IA fournit un retour détaillé sur la qualité du code, la sécurité et les performances.',

    codingBattles: 'Duels de code',
    activeChallenges: 'Défis actifs',
    ranking: 'Classement',
    createChallenge: 'Créer un défi',
    challengeTitle: 'Titre du défi',
    challengeTitlePlaceholder: 'ex. Construire une API REST en 2 heures',
    challengePrompt: 'Énoncé du défi',
    challengePromptPlaceholder: 'Décrivez le défi en détail...',
    challengeType: 'Type de défi',
    communityMatch: 'Communauté (match amical)',
    officialGraded: 'Officiel (travail noté)',
    difficulty: 'Difficulté',
    duration: 'Durée',
    creating: 'Création...',
    titlePromptRequired: 'Le titre et l\'énoncé sont requis.',
    failedCreateChallenge: 'Impossible de créer le défi.',
    anyLanguage: 'Tous',
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    advanced: 'Avancé',
    quickDuration: '2 heures',
    standardDuration: '48 heures',
    royaleDuration: '1 semaine',
    statusPending: 'En attente',
    statusActive: 'Actif',
    statusJudging: 'Évaluation',
    statusComplete: 'Terminé',
    statusPendingDesc: 'En attente du début du duel.',
    statusActiveDesc: 'Les deux joueurs peuvent maintenant soumettre leurs solutions.',
    statusJudgingDesc: 'L\'IA évalue les deux soumissions...',
    statusCompleteDesc: 'Duel terminé. Consultez les résultats ci-dessous.',
    challengePlayer: 'Défier un joueur',
    challengeLabel: 'Défi :',
    selectOpponent: 'Choisir un adversaire',
    searchByName: 'Rechercher par nom...',
    tierLabel: 'Palier :',
    selectOpponentError: 'Veuillez choisir un adversaire à défier.',
    failedInitiateBattle: 'Impossible de lancer le duel.',
    initiating: 'Lancement...',
    initiateBattle: 'Lancer le duel',
    codeArena: 'Arène de code',
    noBattlesYet: 'Aucun duel pour le moment',
    challengeSomeoneText: 'Défiez quelqu\'un depuis l\'onglet Défis pour lancer un duel.',
    noChallengesYet: 'Aucun défi pour le moment',
    firstCreateChallenge: 'Soyez le premier à créer un défi !',
    signInCreateChallenge: 'Connectez-vous pour créer un défi.',
    officialChallenge: 'Défi officiel',
    battle: 'Duel',
    winner: 'Vainqueur',
    defeated: 'Perdu',

    loadingBattle: 'Chargement du duel...',
    battleNotFound: 'Duel introuvable.',
    backToArena: 'Retour à l\'arène',
    player1: 'Joueur 1',
    player2: 'Joueur 2',
    submitted: 'Soumis',
    challengePending: 'Défi en attente',
    challengedText: 'Vous avez été défié dans un duel de code ! Acceptez pour démarrer le minuteur et ouvrir l\'éditeur.',
    acceptChallenge: 'Accepter le défi',
    waitingForAcceptance: 'En attente de l\'acceptation de {name}...',
    liveEditor: 'Éditeur live',
    uploadZip: 'Téléverser ZIP',
    submitYourSolution: 'Soumettre votre solution',
    uploadZipText: 'Téléversez un .zip de votre projet. Gemini AI l\'analysera et le notera immédiatement.',
    uploadingAnalyzing: 'Téléversement et analyse...',
    uploadZipSolution: 'Téléverser la solution .ZIP',
    runCode: 'Exécuter le code',
    executionOutput: 'Sortie d\'exécution',
    processSignal: 'Processus terminé avec le signal {signal}',
    noOutput: 'Programme terminé sans sortie.',
    analyzing: 'Analyse...',
    submitSolution: 'Soumettre la solution',
    waitingOpponent: 'En attente de la soumission de votre adversaire...',
    battleResults: 'Résultats du duel',
    judgingInProgress: 'Évaluation en cours',
    noSubmissionYet: 'Aucune soumission',
    writeSolutionHere: '// Écrivez votre solution ici\n',
    arenaBattleSubmission: 'Soumission de duel arène',
    failedGenerateZip: 'Impossible de générer le fichier ZIP depuis l\'éditeur.',
    executionFailed: 'Échec de l\'exécution',

    liveWebPreview: 'Aperçu web en direct',
    terminalEnvironment: 'Environnement terminal',
    guiPreview: 'Aperçu GUI',
    webPreviewTitle: 'Aperçu web',
    noFilesFound: 'Aucun fichier à exécuter',
    running: 'Exécution...',
    programExited: 'Programme terminé avec le code {code}',
    clickRunCode: 'Cliquez sur "Exécuter le code" pour lancer ce projet dans le bac à sable',
    noScreenshot: 'Aucune capture fournie pour ce projet GUI.',
    uploading: 'Téléversement...',
    uploadScreenshot: 'Téléverser une capture',
    guiCannotRun: 'Les applications GUI ne peuvent pas s\'exécuter dans le navigateur. Lancez-la localement :',
    cloneCommandCopied: 'Commande de clonage copiée !',

    noAnalysisTarget: 'Aucun ID de projet ou de soumission fourni.',
    aiAnalysisFailed: 'Échec de l\'analyse IA. Veuillez réessayer.',
    analyzingInProgress: 'Analyse en cours...',
    reanalyzeWithAi: 'Relancer l\'analyse IA',
    analyzeWithAi: 'Analyser avec l\'IA',

    shareProject: 'Partager le projet',
    shareBattle: 'Partager le duel',
    customMessageOptional: 'Message personnalisé (facultatif)',
    addPersonalMessage: 'Ajouter un message personnel...',
    generateShareLink: 'Générer un lien de partage',
    analytics: 'Statistiques',
    shareAnalytics: 'Statistiques de partage',
    totalClicks: 'Clics totaux',
    uniqueClicks: 'Clics uniques',
    shareDefaultProject: 'Découvrez ce projet sur Evalify !',
    shareDefaultBattle: 'Découvrez ce duel de code sur Evalify !',

    errorBoundaryTitle: 'Oups ! Une erreur est survenue',
    errorBoundaryText: 'Une erreur inattendue est survenue. Notre équipe a été notifiée et travaille sur un correctif.',
    developmentErrorDetails: 'Détails de l\'erreur en développement',
    componentStack: 'Pile de composants :',
    files: 'Fichiers',
    filenamePlaceholder: 'nom-fichier.js',
  },
};

const replaceTokens = (template, values = {}) =>
  String(template).replace(/\{(\w+)\}/g, (_, token) => (
    Object.prototype.hasOwnProperty.call(values, token) ? values[token] : `{${token}}`
  ));

export const translate = (key, lang = 'en', values = {}) => {
  const safeLang = translations[lang] ? lang : 'en';
  const template = translations[safeLang][key] ?? translations.en[key] ?? key;
  return replaceTokens(template, values);
};

export const getStoredLanguage = () => {
  const stored = localStorage.getItem('evalify_lang');
  return translations[stored] ? stored : 'en';
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(getStoredLanguage);

  useEffect(() => {
    localStorage.setItem('evalify_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (nextLang) => {
    setLangState(translations[nextLang] ? nextLang : 'en');
  };

  const value = useMemo(() => ({
    lang,
    setLang,
    t: (key, values) => translate(key, lang, values),
    toggleLanguage: () => setLangState(prev => (prev === 'en' ? 'fr' : 'en')),
  }), [lang]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
